<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<LangVersion>12</LangVersion>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<StaticWebAssetBasePath>/</StaticWebAssetBasePath>
		<ContentTargetFolders>.</ContentTargetFolders>
		<Product>UmbracoPackageTemplate</Product>
		<PackageId>UmbracoPackageTemplate</PackageId>
		<Title>TOKEN_TITLE</Title>
		<Description>TOKEN_DESCRIPTION</Description>
		<PackageTags>umbraco;umbraco-marketplace</PackageTags>
		<Authors>TOKEN_AUTHOR</Authors>
		<Copyright>$([System.DateTime]::UtcNow.ToString(`yyyy`)) © TOKEN_AUTHOR</Copyright>
		<PackageProjectUrl>https://github.com/TOKEN_GITHUB_USERNAME/UmbracoPackageTemplate</PackageProjectUrl>
		<RepositoryUrl>https://github.com/TOKEN_GITHUB_USERNAME/UmbracoPackageTemplate</RepositoryUrl>
        <PackageReadmeFile>README_nuget.md</PackageReadmeFile>
		<RepositoryType>git</RepositoryType>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageIcon>images\icon.png</PackageIcon>
		<NuGetAuditMode>all</NuGetAuditMode>
		<NuGetAuditLevel>high</NuGetAuditLevel>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Umbraco.Cms.Core" Version="15.0.0-rc3" />
        <PackageReference Include="Umbraco.Cms.Api.Common" Version="15.0.0-rc3" />
        <PackageReference Include="Umbraco.Cms.Api.Management" Version="15.0.0-rc3" />
        <PackageReference Include="jcdcdev.Umbraco.Core" Version="15.0.0-alpha0007" />
	</ItemGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <Major>15</Major>
        <Minor>$([System.DateTime]::UtcNow.ToString(`yyyy`))</Minor>
        <Patch>$([System.DateTime]::UtcNow.ToString(`MMdd`).TrimStart(`0`))</Patch>
        <Suffix>-alpha-$([System.DateTime]::UtcNow.ToString(`Hmm-ss`).TrimStart(`.`))</Suffix>
        <PackageVersion>$(Major).$(Minor).$(Patch)$(Suffix)</PackageVersion>
        <Version>$(PackageVersion)</Version>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\..\docs\icon.png" Pack="true" PackagePath="images\icon.png" />
        <None Include="..\..\docs\README_nuget.md" Pack="true" PackagePath="\" />
    </ItemGroup>

</Project>
