name: 🏗️ Build
on:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: jcdcdev/jcdcdev.Umbraco.GitHub.Build@v18
        with:
          project-name: UmbracoPackageTemplate
          project-path: src/UmbracoPackageTemplate/UmbracoPackageTemplate.csproj
          npm-working-dir: src/UmbracoPackageTemplate.Client
          npm-enabled: true
