// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetTestData, GetTestErrors, GetTestResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class TOKEN_CLIENT_NAME {
    public static getTest<ThrowOnError extends boolean = true>(options?: Options<GetTestData, ThrowOnError>): RequestResult<GetTestResponses, GetTestErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetTestResponses, GetTestErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/TOKEN_CLIENT_NAME/api/v1/test',
            ...options
        });
    }
}
