// This file is auto-generated by @hey-api/openapi-ts

export type GetUmbracoTokenClientNameApiV1TestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/TOKEN_CLIENT_NAME/api/v1/test';
};

export type GetUmbracoTokenClientNameApiV1TestResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetUmbracoTokenClientNameApiV1TestResponse = GetUmbracoTokenClientNameApiV1TestResponses[keyof GetUmbracoTokenClientNameApiV1TestResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:54813' | (string & {});
};