// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:54813/' | (string & {});
};

export type GetTestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/TOKEN_CLIENT_NAME/api/v1/test';
};

export type GetTestErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetTestResponses = {
    /**
     * OK
     */
    200: string;
};

export type GetTestResponse = GetTestResponses[keyof GetTestResponses];
