name: Build
on:
  pull_request:
    branches: "*"
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: write
    uses: jcdcdev/jcdcdev.Github.UmbracoSimpleDeploy/.github/workflows/build-template.yml@main
    with:
      project-name: 'jcdcdev.Umbraco.PackageTemplate'
      project-path: './src/jcdcdev.Umbraco.PackageTemplate/jcdcdev.Umbraco.PackageTemplate.csproj'
      npm-enabled: true
      npm-working-dir: './src/jcdcdev.Umbraco.PackageTemplate.Client/'
      npm-run-command: 'build'
    secrets:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}