name: Build
on:
  pull_request:
    branches: "*"
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: write
    uses: jcdcdev/jcdcdev.Github.UmbracoSimpleDeploy/.github/workflows/build-template.yml@main
    with:
      project-name: 'jcdcdev.Umbraco.PackageTemplate'
      project-path: './src/jcdcdev.Umbraco.PackageTemplate.csproj'