name: Release
on:
  pull_request:
    branches: "main"
    types: [ closed ]
  workflow_dispatch:
jobs:
  build:
    uses: jcdcdev/jcdcdev.Umbraco.GitHub.Build@main
    with:
      project-name: 'jcdcdev.Umbraco.PackageTemplate'
      project-path: './src/jcdcdev.Umbraco.PackageTemplate.csproj'
      dotnet-pack: false
      umbraco-version: 13
  release:
    needs:
      - build
    permissions:
      contents: write
    uses: jcdcdev/jcdcdev.Umbraco.GitHub.Release@main 
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      version: ${{ needs.build.outputs.version }}
    secrets:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}